### ISSUE TITLE
Can we have more clarity surrounding install instructions for Windows?

### ISSUE THREAD

**Issue by vdruts** [luciddreamer-cvlab/LucidDreamer#11] opened 2023-12-10 15:38 UTC
Getting this error on second par of install ... 

cd submodules/depth-diff-gaussian-rasterization-min
python setup.py install

----

(luciddreamer) PS C:\Users\xxxx\Deep\LucidDreamer\submodules\depth-diff-gaussian-rasterization-min> python setup.py install
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
running install
C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating depth_diff_gaussian_rasterization_min.egg-info
writing depth_diff_gaussian_rasterization_min.egg-info\PKG-INFO
writing dependency_links to depth_diff_gaussian_rasterization_min.egg-info\dependency_links.txt
writing top-level names to depth_diff_gaussian_rasterization_min.egg-info\top_level.txt
writing manifest file 'depth_diff_gaussian_rasterization_min.egg-info\SOURCES.txt'
C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'depth_diff_gaussian_rasterization_min.egg-info\SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'depth_diff_gaussian_rasterization_min.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-cpython-39
creating build\lib.win-amd64-cpython-39\depth_diff_gaussian_rasterization_min
copying depth_diff_gaussian_rasterization_min\__init__.py -> build\lib.win-amd64-cpython-39\depth_diff_gaussian_rasterization_min
running build_ext
C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\LucidDreamer\submodules\depth-diff-gaussian-rasterization-min\setup.py", line 17, in <module>
    setup(
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\command\install.py", line 80, in run
    self.do_egg_install()
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\command\install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
    return Version(version)
  File "C:\Users\xxxx\anaconda3\envs\luciddreamer\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
(luciddreamer) PS C:\Users\xxxx\Deep\LucidDreamer\submodules\depth-diff-gaussian-rasterization-min>

**Comment by vdruts** [comment] 2023-12-10 15:50
Tried. Pip install . in folder and got:

note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for depth-diff-gaussian-rasterization-min
  Running setup.py clean for depth-diff-gaussian-rasterization-min
Failed to build depth-diff-gaussian-rasterization-min
ERROR: Could not build wheels for depth-diff-gaussian-rasterization-min, which is required to install pyproject.toml-based projects
(luciddreamer) PS C:\Users\xxxx\Deep\LucidDreamer\submodules\depth-diff-gaussian-rasterization-min>

**Comment by esw0116** [comment] 2023-12-10 16:13
Hello, there has been a similar issue opened before.
There is a compiled file uploaded in [here](https://github.com/luciddreamer-cvlab/LucidDreamer/issues/2#issuecomment-1846253744).
Would you please try that file to compile the two submodules?

We will add an installation guide for Windows in ReadME soon.

Duplicate of #2

**Comment by vdruts** [comment] 2023-12-10 22:25
How does one install a .egg file? It says it's deprecated.

(luciddreamer) PS C:\Users\xxxx\Deep\LucidDreamer\submodules> pip install .\simple_knn-0.0.0-py3.10-win-amd64.egg
ERROR: Invalid requirement: '.\simple_knn-0.0.0-py3.10-win-amd64.egg'
Hint: It looks like a path. The path does exist.

Having a hard time installing this... Can't seem to install easy_install :/

**Comment by esw0116** [comment] 2023-12-11 01:18
Sorry to hear the news.
I will figure out how to run the model in Windows environment and update the installation method.

**Comment by Maoku** [comment] 2023-12-11 15:58
I was able to generate ply and render Color/Depth on Windows with the following steps. 
I wanted to make a PullRequest, but I have some ad-hoc fixes, so I’ll write them here.

````
conda create -n lucid_win python=3.9
conda activate lucid_win

# if CUDA_PATH 
set CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8


pip install peft diffusers scipy numpy imageio[ffmpeg] opencv-python Pillow open3d torchvision gradio

conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.8 -c pytorch -c nvidia

pip install timm==0.6.7
pip install plyfile==0.8.1

pip install typing
pip install typing-extensions
pip install chardet

# ninja build
# https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip
# put ninja into some directory in PATH

# copy glm header files
# https://github.com/g-truc/glm/archive/refs/tags/0.9.9.8.zip
# copy glm folder into include path 
# example) .conda\envs\lucid\include\glm

cd submodules/depth-diff-gaussian-rasterization-min
python setup.py install
cd ../simple-knn
python setup.py install
cd ../..
````

The errors that occur at the end of Gaussian Splatting and Rendering Video after execution are due to the intermediate directory not being generated I made some modifications and attached the diff.
I recommend pressing the STEP 1 / STEP 2 button to easily isolate the problem.

````diff
diff --git a/app.py b/app.py
index 1dbc413..606db3b 100644
--- a/app.py
+++ b/app.py
@@ -62,7 +62,7 @@ css = """
 }
 """
 
-ld = LucidDreamer()
+ld = LucidDreamer(save_dir="./outputs/")
 
 
 with gr.Blocks(css=css) as demo:
diff --git a/app_mini.py b/app_mini.py
index 1eaaeea..e1fa7c3 100644
--- a/app_mini.py
+++ b/app_mini.py
@@ -62,7 +62,7 @@ css = """
 }
 """
 
-ld = LucidDreamer()
+ld = LucidDreamer(save_dir="./outputs/")
 
 
 with gr.Blocks(css=css) as demo:
diff --git a/luciddreamer.py b/luciddreamer.py
index b5228a4..53a3780 100644
--- a/luciddreamer.py
+++ b/luciddreamer.py
@@ -60,6 +60,8 @@ class LucidDreamer:
         self.opt = GSParams()
         self.cam = CameraParams()
         self.save_dir = save_dir
+        if self.save_dir is not None:
+            os.makedirs(self.save_dir, exist_ok=True)
         self.for_gradio = for_gradio
         self.root = 'outputs'
         self.default_model = 'SD1.5 (default)'
@@ -218,9 +220,11 @@ class LucidDreamer:
             depthpath = os.path.join('examples', f'depth_{example_name}_{preset}.mp4')
         else:
             if self.for_gradio:
+                os.makedirs(os.path.join(self.root, self.timestamp), exist_ok=True)
                 videopath = os.path.join(self.root, self.timestamp, f'{preset}.mp4')
                 depthpath = os.path.join(self.root, self.timestamp, f'depth_{preset}.mp4')
             else:
+                os.makedirs(os.path.join(self.save_dir), exist_ok=True)
                 videopath = os.path.join(self.save_dir, f'{preset}.mp4')
                 depthpath = os.path.join(self.save_dir, f'depth_{preset}.mp4')
         if os.path.exists(videopath) and os.path.exists(depthpath):

````

environment:Windows11 / VS2022 / RTX 3080Ti / CUDA 11.8

**Comment by esw0116** [comment] 2023-12-11 16:37
@Maoku Thank you so much for your kind explanation!
Actually, I also succeed in executing LucidDreamer in my Windows environment (Windows 11 / VS 2022 / RTX4070Ti / CUDA 11.8)
There are three prerequisite to run the model.

1. CUDA version should match cudatoolkit version for installing pytorch (I use version 11.8).
2. C++ > 14 should be installed in your environment. [Download link](https://visualstudio.microsoft.com/downloads) if you do not have it.
3. clone git package in ``submodules/depth-diff-gaussian-rasterization-min/third_party``. Use the code ``git clone https://github.com/g-truc/glm.git``.

I will polish and update user manual to make it easy for Windows users to run LucidDreamer as well.

**Comment by ironjr** [comment] 2023-12-12 03:05
@Maoku Thank you so much! I will revise the code regarding your contribution.

**Comment by vdruts** [comment] 2023-12-12 03:35
> python setup.py install

Did all of this, but it failed at the last steps still. (Same error as OP)

cd submodules/depth-diff-gaussian-rasterization-min
python setup.py install
cd ../simple-knn
python setup.py install
cd ../..

**Comment by vdruts** [comment] 2023-12-12 03:57
I installed build tools 2022, and rebooted. Seems to have fixed the issue. I had 2019 before.

**Comment by esw0116** [comment] 2023-12-12 05:38
Could you try using the command?: set CUDA_VISIBLE_DEVICES=0 & python run.py
Also, it would be helpful for me to help you solve the problem if you tell us your running environment (Windows version, CUDA version (use command nvcc --version), your GPU model, and the conda installed packages (use command ``conda list``)).

**Closed as completed** 2023-12-13 04:26 UTC

**Comment by vdruts** [comment] 2023-12-13 16:06
Is there a reason why Cuda has to be turned off to run app.py?

**Comment by esw0116** [comment] 2023-12-14 13:12
What does you mean 'turning off CUDA'?
CUDA should not be turned off since gradio app also uses GPU(s) for optimization.
