### ISSUE TITLE
What is the minimum configuration for operation?

### ISSUE THREAD

**Issue by tiandaoyuxi** [luciddreamer-cvlab/LucidDreamer#21] opened 2023-12-13 15:53 UTC
num_rendered, color, depth, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
torch.cuda.OutOfMemoryError: CUDA out of memory. **Tried to allocate 506.54 GiB (GPU 0; 24.00 GiB total capacity; 5.73 GiB already allocated; 15.99 GiB free; 5.93 GiB** reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ws3-01\anaconda3\envs\lucid\lib\site-packages\gradio\queueing.py", line 493, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\ws3-01\anaconda3\envs\lucid\lib\site-packages\gradio\queueing.py", line 464, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

What is the minimum configuration for operation?
Or am I encountering other issues...

**Comment by esw0116** [comment] 2023-12-14 12:50
Duplicate of #22

**Closed as completed** 2023-12-17 09:48 UTC
