### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 270.43 GiB

### ISSUE THREAD

**Issue by mikeyimer** [luciddreamer-cvlab/LucidDreamer#24] opened 2023-12-14 09:04 UTC
In the Windows 10 system, the following error message appears when clicking run:
  
num_rendered, color, depth, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 270.43 GiB

**Comment by esw0116** [comment] 2023-12-14 12:41
I think this issue is same as previously reported issue. (Duplicate of #22)
I will write out the solution after fixing the error.

**Comment by esw0116** [comment] 2023-12-14 12:50
I attribute the error to the wrong installation with whl files.
Installing rasterizer and simple-knn using whl files are now causing unexpected behaviors.
We need some time to fix the whl installation, so please re-create the environment by using the former installation commands.
We have updated the installation process in README.
Sorry for making inconvenience.

**Closed as completed** 2023-12-18 04:26 UTC
