### ISSUE TITLE
How to run the single image to 3D-gs setting (get rid of text prompt)

### ISSUE THREAD

**Issue by zhiwenfan** [luciddreamer-cvlab/LucidDreamer#23] opened 2023-12-14 07:43 UTC
Hello, and thank you for showcasing your impressive work. 

I have an image that I would like to use as input, and I'm interested in understanding how to utilize the run.py script for generating 3D grayscale images (3d-gs) without providing a text prompt. 

Could you please inform me on how to modify the run.py or the command I need to use to achieve this with the provided image?

Thank you for your assistance.

**Comment by esw0116** [comment] 2023-12-14 12:58
Hello, 
Unfortunately, the text prompt plays a crucial role for generating the total scene.
You can use an automatic tagger by AI to generate a proper text prompt. It is introduced in the previous issue. 
Duplicate of #16

**Closed as completed by esw0116** 2023-12-14 12:58 UTC
